// repos/storybook/code/frameworks/angular-vite/template/components/pre.component.ts
import { Component, Input } from '@angular/core';

@Component({
  standalone: false,
  selector: 'storybook-pre',
  template: `
    <pre data-testid="pre" [ngStyle]="style">{{ finalText }}</pre>
  `,
})
export default class PreComponent {
  /** Styles to apply to the component */
  @Input()
  style?: object;

  /** An object to render */
  @Input()
  object?: object;

  /** The code to render */
  @Input()
  text?: string;

  get finalText() {
    return this.object ? JSON.stringify(this.object, null, 2) : this.text;
  }
}

// code/renderers/vue3/template/components/Pre.vue
<template>
  <pre data-testid="pre" :style="style">{{ finalText }}</pre>
</template>

<script>
import { computed, reactive } from 'vue';

export default {
  name: 'my-pre',

  props: {
    // deepscan-disable-next-line
    style: {
      type: Object,
    },
    object: {
      type: Object,
    },
    text: {
      type: String,
      default: '',
    },
  },

  setup(props, { emit }) {
    props = reactive(props);
    return {
      finalText: computed(() =>
        props.object ? JSON.stringify(props.object, null, 2) : props.text
      ),
    };
  },
};
</script>
