// repos/storybook/code/renderers/svelte/src/__test__/composeStories/Button.svelte
<script lang="ts">
  type Props = {
    /**
     * Is this the principal call to action on the page?
     */
    primary?: boolean;

    /**
     * What background color to use
     */
    backgroundColor?: string;

    /**
     * How large should the button be?
     */
    size?: 'small' | 'medium' | 'large';

    /**
     * Button contents
     */
    label?: string;

    /**
     * Button contents
     */
    children?: any;
  };

  const {
    primary = false,
    backgroundColor = undefined,
    size = 'medium',
    label = '',
    children,
    ...props
  }: Props = $props();

  let mode = $derived(primary ? 'storybook-button--primary' : 'storybook-button--secondary');
  let style = $derived(backgroundColor ? `background-color: ${backgroundColor}` : '');
</script>

<button
  type="button"
  class={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
  {style}
  {...props}
>
  {label}
  {@render children?.()}
</button>

// code/frameworks/angular/template/components/button.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  standalone: false,
  // Needs to be a different name to the CLI template button
  selector: 'storybook-framework-button',
  template: `
    <button
      type="button"
      (click)="onClick.emit($event)"
      [ngClass]="classes"
      [ngStyle]="{ 'background-color': backgroundColor }"
    >
      {{ label }}
    </button>
  `,
  styleUrls: ['./button.css'],
})
export default class FrameworkButtonComponent {
  /** Is this the principal call to action on the page? */
  @Input()
  primary = false;

  /** What background color to use */
  @Input()
  backgroundColor?: string;

  /** How large should the button be? */
  @Input()
  size: 'small' | 'medium' | 'large' = 'medium';

  /**
   * Button contents
   *
   * @required
   */
  @Input()
  label = 'Button';

  /** Optional click handler */
  @Output()
  onClick = new EventEmitter<Event>();

  public get classes(): string[] {
    const mode = this.primary ? 'storybook-button--primary' : 'storybook-button--secondary';

    return ['storybook-button', `storybook-button--${this.size}`, mode];
  }
}
