// repos/storybook/test-storybooks/portable-stories-kitchen-sink/svelte/stories/Button.svelte
<script lang="ts">
  import './button.css';
  
  type Props = {
    /**
     * Is this the principal call to action on the page?
     */
    primary?: boolean;
    /**
     * What background color to use
     */
    backgroundColor?: string;
    /**
     * How large should the button be?
     */
    size?: 'small' | 'medium' | 'large';
    /**
     * Button contents
     */
    label?: string;
    /**
     * Optional click handler
     */
    onclick?: (event: MouseEvent) => void;
    /**
     * Button contents
     */
    children?: any;
  };

  const { 
    primary = false,
    backgroundColor = undefined,
    size = 'medium',
    label = '',
    children,
    ...props
  }: Props = $props();

  let mode = $derived(primary ? 'storybook-button--primary' : 'storybook-button--secondary');
  let style = $derived(backgroundColor ? `background-color: ${backgroundColor}` : '');
</script>

<button
  type="button"
  class={['storybook-button', `storybook-button--${size}`, mode].join(' ')}
  {style}
  {...props}
>
  {label}
  {@render children?.()}
</button>

// repos/storybook/code/frameworks/angular-vite/template/stories_angular-cli-prerelease/signal/button.component.ts
import { Component, Input, input, output } from '@angular/core';

@Component({
  standalone: false,
  // Needs to be a different name to the CLI template button
  selector: 'storybook-signal-button',
  template: `
    <button
      type="button"
      (click)="onClick.emit($event)"
      [ngClass]="classes"
      [ngStyle]="{ 'background-color': backgroundColor }"
    >
      {{ label() }}
    </button>
  `,
  styleUrls: ['./button.css'],
})
export default class SignalButtonComponent {
  /** Is this the principal call to action on the page? */
  primary = input(false);

  /** What background color to use */
  @Input()
  backgroundColor?: string;

  /** How large should the button be? */
  size = input('medium', {
    transform: (val: 'small' | 'medium') => val,
  });

  /** Button contents */
  label = input.required({ transform: (val: string) => val.trim() });

  /** Optional click handler */
  onClick = output<Event>();

  public get classes(): string[] {
    const mode = this.primary() ? 'storybook-button--primary' : 'storybook-button--secondary';

    return ['storybook-button', `storybook-button--${this.size()}`, mode];
  }
}
